export enum Constants {
  disabled = 'disabled',
  carAnimationClass = 'car__animation',
  buttonCarViewClass = 'button_car-view',
  buttonPaginationClass = 'button_pagination-view',
  buttonClass = 'button',
  pageBlockClass = 'page__block',
  paginationBlockClass = 'pagination__block',
  tableCellClass = 'td',
  tableRowClass = 'tr',
  mainClass = 'main',
  headerClass = 'header',
  buttonWrapperClass = 'buttons_wrapper',
  carViewClass = 'car-view',
  carCheckViewClass = 'car-view__check-view',
  carTrackClass = 'car-view__track',
  carNameClass = 'car-name__block',
  mainBlockClass = 'main-block',
  winMessageClass = 'win-message__block',
  modalWindowClass = 'modal_window',
  createblockClass = 'create-block',
  garageBlockClass= 'garage-block',
  garageContentClass = 'garage-block_content',
  garageHeaderClass = 'garage-block_header',
  garageRaceClass = 'garage__race-block',
  hideClass = 'hide',
  winnerBlockClass = 'winner-block',
  winnerTableClass = 'winner-table',
  tableHeadClass = 'thead',
  tableBodyClass = 'tbody',
  spanTextClass = 'span_text',
  spanIconClass = 'span-icon',
  countWinBlockClass = 'winner-count_block',
  tableCellButtonClass = 'td_button',

}
